# Generated by Django 3.2.7 on 2021-10-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=30)),
                ('ingredients', models.TextField(max_length=200)),
                ('recipe_method', models.CharField(max_length=30)),
                ('glass', models.CharField(max_length=30)),
                ('process', models.TextField(max_length=200)),
                ('granish', models.TextField(max_length=200)),
                ('notes', models.TextField(max_length=200)),
                ('characteristics', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail.category')),
            ],
        ),
    ]
