# Generated by Django 3.2.7 on 2021-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cocktail', 'cocktail'), ('drink', 'drink'), ('other', 'other')], default='Cocktail', max_length=30),
        ),
    ]
