# Generated by Django 3.2.7 on 2021-10-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='granish',
            new_name='garnish',
        ),
    ]
