# Generated by Django 3.2.7 on 2021-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_rename_granish_recipe_garnish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cocktail', 'cocktail'), ('other', 'other')], default='Cocktail', max_length=30),
        ),
    ]
