# Generated by Django 3.2.7 on 2021-10-03 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='garnish',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='process',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
