# Generated by Django 3.2.7 on 2021-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0007_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
