# Generated by Django 3.2 on 2021-10-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0010_auto_20211011_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='garnish',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
